pipeline {
    agent any 

    stages {
        stage('Dev') {
            steps {

            }
        }
        
        stage('Build') {
            steps {

            }
        }

        stage('Test') {
            steps {

            }
        }
    }
}